spring.application.name=MovieSearchApp

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# This ensures the database persists while the app is running
spring.datasource.url=jdbc:h2:mem:moviedb